### ISSUE TITLE
Add supported features to a board's download page

### ISSUE THREAD

**Issue by siddacious** [adafruit/circuitpython-org#10]
It would be super handy if a person could tell what was supported for a board by looking at its download page.

Extra credit for filtering by feature on the downloads index

**Comment by tannewt** [comment]
Ya totally. A mockup that @tylerdcooper did had little badges on each board.

**Comment by jwcooper** [comment]
Here is that mockup:

![CircuitPython - Downloads](https://user-images.githubusercontent.com/311256/54142957-cbb28180-43f6-11e9-916b-96143b78278c.png)

**Comment by deshipu** [comment]
Badges might be a little difficult to search for and filter by.
