### ISSUE TITLE
ESP32-S3: Add information on using the UF2 bootloader

### ISSUE THREAD

**Issue by kmatch98** [adafruit/circuitpython-org#1001]
The ESP32-S3 board descriptions explain how to install the UF2 bootloader.

I recommend adding details on how to trigger into UF2 bootloader mode:

1. Click RESET
2. While purple LED is lit, click BOOT. (LED will flash red and then remain green.)
3. `S3DKC1BOOT` drive should appear

Also, it may be helpful to indicate that you should connect to the UART port to flash the UF2 boot loader. And then after that is complete that you then connect to the USB port when using the UF2 boot loader to get to the S3….BOOT drive or the CIRCUITPy drive

**Comment by dglaude** [comment]
Thank you for this.
I was desperated and every time I have to use esptool to upload the bin file... just because I did not knew that trick.
Thanks.
I guess that works for most Espresif... it deserve to be known.

**Comment by dhalbert** [comment]
@kattni How about we add specific info on the "CircuitPython Quickstart" and "Installing UF2 Bootloader" Learn Guide templates that double-clicking on the Espressif boards involves waiting for the purple. I myself didn't know this a few months ago and was stymied until I was told.

**Comment by kattni** [comment]
I updates all the guide templates and the applicable guides to reflect the purple LED bootloader indicator.
