### ISSUE TITLE
Add guide link for ESP32 boards

### ISSUE THREAD

**Issue by HelenFoster** [adafruit/circuitpython-org#1034]
Currently the download pages for the ESP32 boards don't give any instructions, but I was directed to this page when I asked in the Discord.

https://learn.adafruit.com/circuitpython-with-esp32-quick-start

**Comment by makermelissa** [comment]
Good idea. I believe there is currently a place to stick a link to a guide (at least on the blinka boards), but I don't think the website actually shows this link currently, so that should be fixed at the same time.

**Comment by makermelissa** [comment]
Reminder: Move guide link into metadata that was added in #1045 while adding this.
