### ISSUE TITLE
Don't deploy "original" images

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython-org#1057]
The pages deployment deploys all the versions of the board images: `original/`, `large/`, and `small/`, but I don't see that the `original/` images are linked anywhere. Some of those are very large, and cause the deployment artifact to be over 300MB. The deployment takes many minutes. Could we avoid deploying that directory?

**Comment by makermelissa** [comment]
I think it just needs to be added to https://github.com/adafruit/circuitpython-org/blob/main/_config.yml#L45. I believe the original purpose was transitional when we were starting to optimize, though it is nice to have the originals available. We now have scripts to ensure the small and large images are there, so I think it's reasonable to exclude it, though I think a couple places that try to load it as a backup may need to be updated too.
