### ISSUE TITLE
Hacktoberfest appears twice in Issues sort dropdown

### ISSUE THREAD

**Issue by prcutler** [adafruit/circuitpython-org#1060]
On the Contribution page:  https://circuitpython.org/contributing/open-issues?label=hacktoberfest

The issue sort drop down shows Hacktoberfest twice.  Kattni wasn't sure if it was related to the label or an org issue.  The results appear to be the same when clicking either

![Screen Shot 2022-10-04 at 11 48 09 AM](https://user-images.githubusercontent.com/67276/193885248-d0910fe1-3e76-4d1a-a269-bc84154638e4.png)

**Comment by prcutler** [comment]
It might be a capitalization issue as I see two different tags in the list, with and without a capital H
<img width="752" alt="Screen Shot 2022-10-04 at 4 49 30 PM" src="https://user-images.githubusercontent.com/67276/193937020-5ae43aea-988c-4890-be42-b2d8b40466b2.png">

**Comment by makermelissa** [comment]
Good catch. I wonder if just adding the downcase filter to https://github.com/adafruit/circuitpython-org/blob/main/contributing/open_issues.html#L16 might fix it.
