### ISSUE TITLE
Pi Pico GP15 OK now?

### ISSUE THREAD

**Issue by HelenFoster** [adafruit/circuitpython-org#1083]
https://circuitpython.org/board/raspberry_pi_pico/ says "You get a total of 25 GPIO pins (technically there are 26 but IO `#15` has a special purpose and should not be used by projects)", but I believe that was fixed a while ago.

**Comment by HelenFoster** [comment]
This is about Pico and I think the linked PR is only about Pico W.

**Comment by makermelissa** [comment]
Oops, yeah. Was this a hardware or software fix?

**Comment by makermelissa** [comment]
Never mind, I found what you're referring to: https://github.com/earlephilhower/arduino-pico/discussions/364#discussioncomment-1750308

**Comment by HelenFoster** [comment]
https://github.com/adafruit/circuitpython/issues/4107

>I removed the auto close mention.

Looks like the PR is still linked though.

**Comment by makermelissa** [comment]
> [adafruit/circuitpython#4107](https://github.com/adafruit/circuitpython/issues/4107)
> 
> > I removed the auto close mention.
> 
> Looks like the PR is still auto-close linked though.

I fixed it and re-linked.
