### ISSUE TITLE
Adabot submodule needs to be fixed and repinned

### ISSUE THREAD

**Issue by tekktrik** [adafruit/circuitpython-org#1091]
The cron the updates the contributing information is failing because Adabot's current method of using validators is failing for Python 3.11.  I've submitted https://github.com/adafruit/adabot/pull/309 for this - hopefully that's the only change needed.  After that's merged, the `adabot` submodule should be updated here.

**Comment by tekktrik** [comment]
Looks like this wasn't enough - I think it may be worth pinning the Python version similar to the way Adabot does to Python 3.9.  If so, should it be penultimate (3.10) or the same as Adabot (3.9)?

**Comment by makermelissa** [comment]
Sure. In here? https://github.com/adafruit/circuitpython-org/blob/main/.github/workflows/adabot_cron.yml

**Comment by tekktrik** [comment]
Yup! For reference, the BigQuery package adabot now needs isn't avialable for Python 3.11 yet.

**Comment by tekktrik** [comment]
Linking https://github.com/googleapis/python-bigquery/issues/1386 so we can track it potentially

**Comment by makermelissa** [comment]
I see there were a couple of related PRs. Is this fixed now?

**Comment by tekktrik** [comment]
Yup!  Thanks for catching!
