### ISSUE TITLE
crcibernetica_ideaboard.md or crcibernetica-ideaboard.md

### ISSUE THREAD

**Issue by dglaude** [adafruit/circuitpython-org#1104]
On page
https://circuitpython.org/board/crcibernetica_ideaboard/
If you click on "here" of this sentence:
"Have some info to add for this board? Edit the source for this page here."
You get to this page that is a 404:
https://github.com/adafruit/circuitpython-org/edit/main/_board/crcibernetica-ideaboard.md
And the proper link is with a "_" rather than a "-":
https://github.com/adafruit/circuitpython-org/edit/main/_board/crcibernetica_ideaboard.md

There is sure place for confusion on "-" vs "_" but I am not sure how the contribute link is generated, so I don't really see how to fix it.

Regards

**Comment by makermelissa** [comment]
Ah, good catch. It's in https://github.com/adafruit/circuitpython-org/blob/main/_layouts/download.html and should be a pretty simple fix.
