### ISSUE TITLE
No stable release?

### ISSUE THREAD

**Issue by mjuniper** [adafruit/circuitpython-org#1126]
On [this page](https://circuitpython.org/board/adafruit_feather_esp32s3_tft/), it lists the latest _unstable_ release at the top. Then farther down it says you should use the latest stable release. But I can't for the life of me find a download of _any_ stable release for that board.

I can't tell if this is a bug or if this is simply because there is no stable release for that board (maybe because it is new-ish?).

**Comment by dhalbert** [comment]
Right, this board was added on the 8.0.0 line, and will not be backported to 7.x.x. So even if a 7.3.4 came out, it would not have this board.

We're hoping for a stable release for 8.0.0 relatively soon, but in the meantime, it's fine to try the 8.0.0 betas.

**Comment by makermelissa** [comment]
Closing because this isn't a bug.
