### ISSUE TITLE
Spacing between Previous Versions of CircuitPython Buttons

### ISSUE THREAD

**Issue by makermelissa** [adafruit/circuitpython-org#1141]
There appears to be no spacing between the buttons in the `Previous Versions of CircuitPython` box
<img width="609" alt="Screen Shot 2023-02-03 at 8 28 32 AM" src="https://user-images.githubusercontent.com/2681417/216655753-22faea9f-9cb2-4f64-8ec3-9f1c0cb208df.png">

**Comment by dhalbert** [comment]
One was `<p>` and one was `<div>`. I made them both `<div>` for consistency, but that was a bad idea.

**Comment by makermelissa** [comment]
It's all good. I already fixed it with CSS and combined it in the CP Installer I'm working on, which is why I self-assigned.

**Comment by makermelissa** [comment]
This was fixed in #1137.
