### ISSUE TITLE
Board feature "Castellated Pads" would be a useful filter

### ISSUE THREAD

**Issue by evildave666** [adafruit/circuitpython-org#1163]
There are currently (from visual inspection of the photos) at least 40 boards with castellated pads. It would be nice to have it be a board feature in order to be able to filter to help decide what to use.

**Comment by makermelissa** [comment]
Yeah, that sounds like a good feature to add. Would you like to go through the boards and submit a PR? Don't forget to update https://github.com/adafruit/circuitpython-org/blob/main/template.md so it will pass the checks. Afterwards, I can update the guide.

**Comment by johnnohj** [comment]
Following up from Pull Request #1446 to echo support for including "Castellated Pads" and to propose including "Trinkey Form Factor" or similar to denote a board's capacity for direct-to-host machine connection via integrated PCB USB-A plug.
