### ISSUE TITLE
Hidden board adafruit_feather_rp2040_usb_host

### ISSUE THREAD

**Issue by dglaude** [adafruit/circuitpython-org#1188]
I suspected some hardware problem with my "Feather RP2040 USB-HOST":
* the green LED to power the USB HOST was never going green.

So I wanted to check in CircuitPython because at least there I more or less know what I am doing. (and that did permit me to know that my board is likely OK)

I found an "old" image in the learn guide, and I found we generate images for that board in  https://adafruit-circuit-python.s3.amazonaws.com/index.html?prefix=bin/adafruit_feather_rp2040_usb_host/en_US/
But this is "hidden" and there is no page/board in circuitpython.org.

Maybe this is intended, because we don't want user to believe it is supported in CP and then discover USB-HOST part is not supported in CP.
Maybe Kattni or Liz needed the UF2 for the learn guide an a quick hack was done (see https://learn.adafruit.com/adafruit-feather-rp2040-with-usb-type-a-host/circuitpython that has a link to github artifact).

Or it will become visible as soon as there is a new alpha/beta release of 8.1?

I don't know, something is a bit special about this board, and maybe it is intended. I just try to understand, or attract attention if it is not intended.

**Comment by Neradoc** [comment]
Hi, build artifacts from merged PRs are uploaded to Amazon S3 with the board ID, which is the name of the board directory in the Circuitpython repository, and the path in the URL used on circuitpython.org. That is the S3 link you mention.
The board list on circuitpython.org is only updated when there's a release, unless a board is added manually in which case it will be listed at the end, with no release but a link to "Absolute newest" (which might not work if there is no finished build yet).
