### ISSUE TITLE
Downloading ThinkInk UF2 results in NoSuchKey error

### ISSUE THREAD

**Issue by prcutler** [adafruit/circuitpython-org#1199]
From the ThinkInk page at https://circuitpython.org/board/adafruit_feather_rp2040_thinkink/ if you click the `Download .UF2 Now` button an error page pops up that says:

```
NoSuchKeyThe specified key does not exist.bin/adafruit_feather_rp2040_thinkink/en_US/adafruit-circuitpython-adafruit_feather_rp2040_thinkink-en_US-8.1.0-beta.2.uf2Q10MMZEDH3FGDR91oJjfGeJ70KCpvG+NzmmXEvh1OazNg1JlhRijglVqWem8ZZcRfGu3tYQReYewKMt94qg1llCMqTU=
```

**Comment by tannewt** [comment]
I used to be called `adafruit_feather_rp2040_epd` but will be `thinkink` in the next update.
