### ISSUE TITLE
image missing from https://circuitpython.org/awesome

### ISSUE THREAD

**Issue by ptorrone** [adafruit/circuitpython-org#120]
image missing from https://circuitpython.org/awesome looks like ya'll are on it, here is the issue.

![adafruit_2019_1766](https://user-images.githubusercontent.com/1685947/55690666-8dab6d80-5962-11e9-88b4-3e71aeda18e9.jpg)

**Comment by dhalbert** [comment]
This was fixed by #114, but somehow the site hasn't been rebuilt, which I don't understand.

**Comment by sommersoft** [comment]
I can't speak to the site building after no.114 or not as I can't even see that side of things. But, could it maybe be related to the image source URL?

Its currently `https://github.com/adafruit/awesome-circuitpython/blob/master/awesome_circuitpython.png`. Navigating to that URL in a browser brings up the repo, not just the image.

Maybe the download URL would be better? `https://raw.githubusercontent.com/adafruit/awesome-circuitpython/master/awesome_circuitpython.png`
