### ISSUE TITLE
Is there two ThinkInk board?

### ISSUE THREAD

**Issue by dglaude** [adafruit/circuitpython-org#1209]
Maybe something went wrong, because those two board seems to be the same where "ePaper Display" = "ThinkInk":
* https://circuitpython.org/board/unknown/?unknown_id=adafruit_feather_rp2040_thinkink
* https://circuitpython.org/board/adafruit_feather_rp2040_epd/

**Comment by makermelissa** [comment]
Nah, the name was recently changed and the old one (epd) wasn't completely removed from the data file.
