### ISSUE TITLE
locals() does not work the same as Python 3.10

### ISSUE THREAD

**Issue by BNNorman** [adafruit/circuitpython-org#1222]
I am converting a Python program and came across a problem with locals() not working as expected.

test code

```
def showLocals(A=None, B=None, C=None):
       print("Locals",locals())
       print(f"A={A} B={B} C={C}")
        
showLocals(A=1, B=2, C=3)
```

with CircuitPython 8.2.0 I get the following output

```
Locals {'showLocals': <function showLocals at 0x2000b190>, '__name__': '__main__', '__file__': '<stdin>'}
A=1 B=2 C=3
```

Whereas, with Python 3.10  I get this:-

```
Locals {'A': 1, 'B': 2, 'C': 3}
A=1 B=2 C=3
```

I can work around this but. nevertheless, CircuitPython should do the same as Python, I would have thought. 

Regards
Brian

**Comment by dhalbert** [comment]
This is a difference we inherited from MicroPython. See https://docs.micropython.org/en/latest/genrst/core_language.html#local-variables-aren-t-included-in-locals-result. This difference saves time and space.
