### ISSUE TITLE
RP2040-LCD-1.28 - can't run slideshow example

### ISSUE THREAD

**Issue by Luix333** [adafruit/circuitpython-org#1258]
Hi, I don't have a loot of experience on this, so please let me know if I should be posting this elsewhere.

I haven't been able to replicate a simple slideshow example. My screen remains blank the whole time (I know the board and screen are working because I'm able to successfully follow waveshare demos; Arduino, C, and micropython). I'm trying to run the exact same code and steps as the tutorial (even using the images provided in the tutorial) but nothing. I have a feeling that maybe the display is not set up correctly? Like I said I'm a noob at this and would appreciate any help.

Board: [RP2040-LCD-1.28](https://www.waveshare.com/wiki/RP2040-LCD-1.28)
CircuitPython version: [8.2.6](https://circuitpython.org/board/waveshare_rp2040_lcd_1_28/)
Slideshow Example: [tutorial](https://learn.adafruit.com/creating-slideshows-in-circuitpython/use-it)
Waveshare Demos: [files](https://files.waveshare.com/upload/9/9d/RP2040-LCD-1.28.zip)

**Comment by makermelissa** [comment]
Hi, issues posted here are for issues with the website. For help, I'd suggest posting in the support forums at https://forums.adafruit.com/ or chatting via discord at http://adafru.it/discord
