### ISSUE TITLE
Wrong version ESP32 page https://circuitpython.org/board/espressif_esp32c6_devkitc_1_n8/ heading says it's for ESP32-S3-DevKitC-1-N8

### ISSUE THREAD

**Issue by Anutrix** [adafruit/circuitpython-org#1271]
### CircuitPython version

```python
9.0.0 Beta. NA?
```

### Code/REPL

```python
# NA
```

### Behavior

https://circuitpython.org/board/espressif_esp32c6_devkitc_1_n8/ **HEADING** says it's for ESP32-S3-DevKitC-1-N8.
![image](https://github.com/adafruit/circuitpython/assets/11459028/ba33e010-8ba8-4e61-9b7f-b2e23af15707)

It shows up in search results(https://circuitpython.org/downloads?q=esp32-s3-devkitc-1-n8) too:
![image](https://github.com/adafruit/circuitpython/assets/11459028/dd57defa-380c-49af-9e7c-cbd2b99c15c6)
It goes to https://circuitpython.org/board/espressif_esp32c6_devkitc_1_n8/.

I'm still not sure if it's for ESP32-S3-DevKitC-1-N8 or ESP32-C6-DevKitC-1-N8.

Won't flashing wrong firmware break stuff?

### Additional information

Wasn't sure where to report so reporting here.

**Comment by makermelissa** [comment]
This one is the ESP32-C6-DevKitC-1-N8. I'm submitting a PR to fix the name.
