### ISSUE TITLE
add LIBRARIES to the top

### ISSUE THREAD

**Issue by ptorrone** [adafruit/circuitpython-org#13]
add LIBRARIES to the top, after DOWNLOADS on https://circuitpython.org/ and link to: https://github.com/adafruit/Adafruit_CircuitPython_Bundle/blob/master/circuitpython_library_list.md

download the road maybe we can just render that page on a page on https://circuitpython.org/ like .libraries.hml

**Comment by jwcooper** [comment]
Added with https://github.com/adafruit/circuitpython-org/commit/4a661a3c22b38caaedfb9b2f714ce2f4ca20856f
