### ISSUE TITLE
Lilygo T-DECK

### ISSUE THREAD

**Issue by Freyr86** [adafruit/circuitpython-org#1306]
Good morning,

In order to use the LoRa module of the T_Deck it would be necessary to be able to revup the SPI object of the screen because it is not possible to create another SPI controller without having an "Occupy" response on the IO40 PIN which manages the clock of the two modules.

What is the corresponding SPI object

**Comment by makermelissa** [comment]
Please contact Lilygo for support. This is for circuitpython.org website related issues.

**Comment by Freyr86** [comment]
No, it is indeed a python circuit which does not allow the use of several SPI peripherals. I can do it in C++ compiler but the scripting does not authorize it.
