### ISSUE TITLE
RSS Board Feed not showing most recent boards first

### ISSUE THREAD

**Issue by DJDevon3** [adafruit/circuitpython-org#1354]
I would like to see the RSS feed in the top right corner of the CircuitPython.org website to be updated with the latest added boards. This means sorting the RSS feed in chronological order.  Most people expect an RSS feed to be in chronological order.  

The alphabetical RSS feed gives the appearance of not being updated since May 2023 if the expectation is that an RSS feed is in chronological order.  It gives the appearance of a dead RSS feed.

![Capture](https://github.com/adafruit/circuitpython-org/assets/49322231/58016c09-7ddb-4bfa-85e8-a92fad0878eb)

**Comment by dhalbert** [comment]
So we would sort it by `<pubDate>`, most recent first.

**Comment by makermelissa** [comment]
Yeah, that RSS feed is sorting correctly.

**Comment by DJDevon3** [comment]
Today is March 22, 2024 so this looks to be updated with the latest boards. Now I have an RSS feed for CircuitPython.org latest added boards. This is great! Thank you.

![Capture](https://github.com/adafruit/circuitpython-org/assets/49322231/1902b19c-595c-434b-b8df-645d02ad4b60)
