### ISSUE TITLE
Lolin S3 PRO - bootloader download link broken

### ISSUE THREAD

**Issue by PaulskPt** [adafruit/circuitpython-org#1377]
See page: [Lolin S3 PRO](https://circuitpython.org/board/lolin_s3_pro/), section: ```Install, Repair, or Update UF2 Bootloader```, at bottom of the page the link: ```DOWNLOAD BOOTLOADER.ZIP``` is broken. Reports ```not found```.

As a workaround I downloaded the bootloader.zip for the ```Lolin S3``` which works OK for the Lolin S3 PRO.

**Comment by FoamyGuy** [comment]
The download bootloader zip button is now working properly and does download the appropriate file.
