### ISSUE TITLE
Correct some errors

### ISSUE THREAD

**Issue by EthanPal** [adafruit/circuitpython-org#1477]
Dear Team,

I would like to correct some errors on the following pages:

https://circuitpython.org/board/esp32-wrover-dev-cam/
https://github.com/adafruit/circuitpython-org/blob/main/_board/esp32-wrover-dev-cam.md

The AliExpress link provided on the above pages are not genuine products, they are counterfeit.

Please replace the AliExpress link with the official Freenove store link:

https://www.aliexpress.com/item/3256804153608796.html

Please also replace the product image.

Thank you!

**Comment by tannewt** [comment]
@EthanPal Please make a pull request with the changes.

**Comment by EthanPal** [comment]
OK, thank you!
