### ISSUE TITLE
Download buttons missing from libraries page on desktop browsers

### ISSUE THREAD

**Issue by kattni** [adafruit/circuitpython-org#176]
@jwcooper The bundle download buttons are missing from the Libraries page, only on desktop browsers (mobile works). I verified it on Chrome on Linux, and Firefox on Mac and Linux.

If you could take a look, that would be great. Thanks!

<img width="1270" alt="Screen Shot 2019-05-02 at 2 54 47 PM" src="https://user-images.githubusercontent.com/7865090/57099656-f4fed800-6cea-11e9-93c1-a7ac8829cbdf.png">

**Comment by jwcooper** [comment]
Do you have any ad-blocking software that is preventing the github api from loading (privacy badger, ertc)? Any errors in the javascript console? I tested all three major browsers, and it's loading OK (on mac OS).

**Comment by tannewt** [comment]
I see the buttons on Mac with Firefox too.

**Comment by kattni** [comment]
This has continued to happen inconsistently, but for the most part, it's not happening. I'm going to close this for now and if I keep running into it, I'll reopen.
