### ISSUE TITLE
boards: blip: how to show hex (or bin) download link on board page?

### ISSUE THREAD

**Issue by ntavish** [adafruit/circuitpython-org#240]
Blip doesn't use a bootloader since it has bootloader on board, however there is only `.UF2` link on board page. I do see that some boards do have a `.bin` download link (maybe even `.hex`), for example: https://circuitpython.org/board/pca10059/.

What needs to change to blip's page to make that happen?

**Comment by ntavish** [comment]
Looks like I need hex file to be generated by editing `circuitpython/tools/build_board_info.py`. Will close once that happens.

**Comment by ladyada** [comment]
thanks :)

**Comment by ntavish** [comment]
Closing as it should change link on next release. https://github.com/adafruit/circuitpython/commit/7f97cc19408c50d2c2fb53c9bc82ae24da5a4b0d
