### ISSUE TITLE
Feature Request: Sort by Date Added

### ISSUE THREAD

**Issue by TheKitty** [adafruit/circuitpython-org#299]
Suggestion for CircuitPython.Org/downloads - sort by date board added - get the newest first

phillip torrone 11:59 AM
yah, add that as a feature request as an issue in github
would be, click the filter button
then..
Sort By
Downloads
Board Name (A To Z)
Board Name (Z To A)
adding Date (Most recent)

**Comment by jwcooper** [comment]
This also sort of ties into the RSS feed issue (https://github.com/adafruit/circuitpython-org/issues/291) as we need a way to sort by newly added boards to add to the RSS feed. One option would be to add a date field to each _board/* file as we add them.

**Comment by makermelissa** [comment]
First part of this is done: downloads via #437.
Next up is the Blinka boards.
