### ISSUE TITLE
Add label data to libraries.json for inclusion in Contributing

### ISSUE THREAD

**Issue by kattni** [adafruit/circuitpython-org#306]
Please include the GitHub issue label data in the libraries.json file used to generate /libraries/contributing so we can include an option in the UI to filter by label.

**Comment by sommersoft** [comment]
Pre-PR request for comment. @jwcooper, does this format work for you?
```
"Adafruit_CircuitPython_Bitmap_Font": [
      {
        "title": "TTF support (Open 147 days)",
        "url": "https://github.com/adafruit/Adafruit_CircuitPython_Bitmap_Font/issues/10",
        "labels": [
          "None"
        ]
      },
      {
        "title": "Remove backward-compatible imports when 4.0.0 released (Open 203 days)",
        "url": "https://github.com/adafruit/Adafruit_CircuitPython_Bitmap_Font/issues/9",
        "labels": [
          "Hacktoberfest",
          "good first issue"
        ]
      }
    ],
```

Old format for reference:
```
"Adafruit_CircuitPython_ADS1x15": [
      {
        "https://github.com/adafruit/Adafruit_CircuitPython_ADS1x15/issues/40": "Can cause crashes when used with multiple threads at once - thread-safety (Open 6 days)"
      },
```

**Comment by jwcooper** [comment]
Yes, that looks good to me at first glance!

Would it be possible to name this new format something like libraries.v2.json so that we don't break the site while we transition to the new format?

**Comment by sommersoft** [comment]
> Would it be possible to name this new format something like libraries.v2.json so that we don't break the site while we transition to the new format?

Definitely. Will make that happen when pulling in the updated adabot submodule.
