### ISSUE TITLE
add pictures and md page for sparkfun_qwiic_micro with and without flash

### ISSUE THREAD

**Issue by ladyada** [adafruit/circuitpython-org#317]
`@edspark I'll get the pictures and .md page added sometime tomorrow! Thanks @ladyada`

**Comment by ladyada** [comment]
tagging @edspark here so they have the assignment

**Comment by edspark** [comment]
Works for me, unfortunately this will have to wait till Monday, but it's at the top of my list. Have a great weekend!

**Comment by edspark** [comment]
Pull request [here](https://github.com/adafruit/circuitpython-org/pull/321).

**Comment by edspark** [comment]
Can we close this out since the pull request was accepted?

**Comment by makermelissa** [comment]
Almost... I'm applying a fix and then we can...

**Comment by makermelissa** [comment]
Ok, fixed.

**Comment by ladyada** [comment]
yay thanks folks - @edspark we needed to make two entries because there are two builds that were defined. please check https://circuitpython.org/downloads

**Comment by makermelissa** [comment]
It also wanted very specific names for the boards.

**Comment by edspark** [comment]
Thank you for updating that!
