### ISSUE TITLE
Add RSS link to head

### ISSUE THREAD

**Issue by ptorrone** [adafruit/circuitpython-org#365]
@jwcooper as ya do updates to the head-area please add 

```<link rel="alternate" type="application/rss+xml" title="CircuitPython news!" href="https://blog.adafruit.com/category/circuitpython/feed/" />```

to head on circuitpython.org

this way it'll show up in rss readers, etc.

**Comment by jwcooper** [comment]
Added in: https://github.com/adafruit/circuitpython-org/pull/367

**Comment by ptorrone** [comment]
thanks!
