### ISSUE TITLE
Add learn guide links to all Adafruit boards

### ISSUE THREAD

**Issue by iayanpahwa** [adafruit/circuitpython-org#385]
It'll be convenient to have hyperlinked learn guides to Adafruit portal for contributed boards from Adafruit.

**Comment by makermelissa** [comment]
Sounds like this would be similar to the Blinka pages. Good idea.

**Comment by iayanpahwa** [comment]
@makermelissa As in these? [https://circuitpython.org/blinka](https://circuitpython.org/blinka). I can create a PR.

**Comment by makermelissa** [comment]
Exactly.

**Comment by iayanpahwa** [comment]
@rasponicc , I know you have been wanting to contribute to CircuitPython, would you like to take this one up as a good first issue? I’m certain maintainers will help you out when needed.

cc @makermelissa , @ladyada , @dhalbert

**Comment by ladyada** [comment]
will definitely help, this is an excellent beginner issue :)

**Comment by rasponicc** [comment]
Yes, will love to! Thanks!

**Comment by iayanpahwa** [comment]
@makermelissa can you assign this issue to her? (@rasponicc)

**Comment by rasponicc** [comment]
So learn guide exists on 1 board out of all(see: https://circuitpython.org/board/circuitplayground_express/). The other way of creating the learn guide is adding a section to the right side of the page(ref: file. look at the right hand side). Which way should I go about to add the learn guide across all board? I feel the first one, that is already there for **Circuit playground express** board on the website will work better in terms of quick readability, fast access(without the viewer having to look for it) on both pc and mobile platform.
![cktpython](https://user-images.githubusercontent.com/11389424/73268052-3b448180-4200-11ea-9063-67131ac4785e.png)

**Comment by iayanpahwa** [comment]
@rasponicc thanks for taking this up. I would like to see the approach in the screenshot having a dedicated button attracts the eye and visitor will not have to skim through a lot of texts where eyes often get lost. Also you may try both? Hyperlinking under Tutorials tab and making a dedicated session as can be seen in the screenshot, also I was thinking of hyperlinking the main board cover photo with the learn guide. We can have all three maybe!

The tutorials tab (on the left) may in future be used to add a lot of tutorials using that board from Adafruit's learning system and other users blog so having a dedicated button at the right looks a charm to eyes. 

thoughts? @ladyada , @makermelissa

**Comment by rasponicc** [comment]
PR created #420
