### ISSUE TITLE
Unknown Boards with CP5 Beta 5

### ISSUE THREAD

**Issue by makermelissa** [adafruit/circuitpython-org#399]
It looks like the following boards are missing:
ndgarage_ndbit6
meowbit_v121

Issue #396 is already open for the ndbit6, but since there hasn't been any movement on it, I may just try and get something up in the meantime.

**Comment by makermelissa** [comment]
Ok, it appears `kittenbot_meowbit` was renamed to `meowbit_v121` since `kittenbot_meowbit` no longer appears in the assets. @hierophect, can you confirm?

**Comment by hierophect** [comment]
@makermelissa I've always had it as `meowbit_v121` - where did `kittenbot_meowbit` come from? I'm happy to switch to that if needed.

**Comment by makermelissa** [comment]
Thanks @hierophect. I probably saw it was named that in the circuitpython boards at some point. No problem, I can change it on my end.
