### ISSUE TITLE
Add UARTLogger2 to circuitpython.org website

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython-org#431]
Added to circuitpython 5.1.0 https://github.com/adafruit/circuitpython/pull/2705

@nightskysk can you help us out?  There's a guide here: https://learn.adafruit.com/how-to-add-a-new-board-to-the-circuitpython-org-website

**Comment by makermelissa** [comment]
@NightSkySK, if you could at least provide a good photo and some information on the board, I could put something together, but if you're able to submit a PR, that'd even be better. Thanks.

**Comment by makermelissa** [comment]
Since there's no info that I can add, I'll create a hidden stub for this so it doesn't show up on the website as unknown for now.

**Comment by makermelissa** [comment]
This is now hidden. @NightSkySK please submit a PR if you want it shown to the world. Closing for now.
