### ISSUE TITLE
Add TG-Watch02A to circuitpython.org website

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython-org#432]
Added to circuitpython 5.1.0 https://github.com/adafruit/circuitpython/pull/2695

@TG-techie can you help us out?  There's a guide here: https://learn.adafruit.com/how-to-add-a-new-board-to-the-circuitpython-org-website

**Comment by makermelissa** [comment]
@TG-Techie, if you could at least provide a good photo and some information on the board, I could put something together. Thanks.

**Comment by TG-Techie** [comment]
@makermelissa  I'll gladly try to add it. should i discord you if i have any trouble?

**Comment by makermelissa** [comment]
Thanks @TG-Techie. Just reply to this issue if you do.

**Comment by makermelissa** [comment]
I'll create a hidden stub for this so it doesn't show up on the website as unknown for now.

**Comment by makermelissa** [comment]
This is now hidden. @TG-Techie please submit a PR if you want it shown to the world. Closing for now.
