### ISSUE TITLE
Add or Hide Unknown Boards on website

### ISSUE THREAD

**Issue by makermelissa** [adafruit/circuitpython-org#450]
The following boards are showing as unknown. I should be able to find some info about at least a couple of these. @theacodes, do you want to submit a PR for winterbloom_big_honking_button? We have a guide available at https://learn.adafruit.com/how-to-add-a-new-board-to-the-circuitpython-org-website

winterbloom_big_honking_button
fomu
bdmicro_vina_m0
thunderpack

**Comment by theacodes** [comment]
I'll be sending a PR shortly, waiting on better pictures. :)

**Comment by makermelissa** [comment]
Awesome! Thank you

**Comment by makermelissa** [comment]
Remaining board links:
https://www.adafruit.com/product/4332
https://github.com/jgillick/ThunderPack/tree/STM32F4
https://bdmicro.com/products/vina-m0
