### ISSUE TITLE
Download language dropdown not working

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython-org#50]
The Javascript for changing the anchor link on the download button based on the language dropdown isn't working. The Javascript is set up to change `<a class="download-button">`, but that class is used for the link to the release itself, in the "Past Releases" section. The dropdowns for the stable and unstable releases aren't changing the URL for their respective buttons, which are `<a class="download-button-{{stable}}"> in the template code. And I think maybe it should be `{{version.stable}}` as well?

**Comment by sommersoft** [comment]
After @jerryneedell pointed out that the download link actually changes for the `Past Releases` button, I think I see the issue. (_I said that yesterday too, but maybe this time the result is better?_ 😄)

The `Past Releases` class name is `download-button`, whereas the current unstable release class name is `download-buttons`.

There is a JS that handles updating the link based on the language selection, and it appears to be pointing to the incorrect class: [`document.querySelector(".download-button").href = languageSelect.value;`](https://github.com/adafruit/circuitpython-org/blob/1fd695126698a38c8558f57f4706c7ec6e252938/assets/javascript/download.js#L14)

All it needs is an `s` added to the target class, and it _should_ fix it?
