### ISSUE TITLE
Use dark background board image where possible.

### ISSUE THREAD

**Issue by dglaude** [adafruit/circuitpython-org#513]
I have a new screen with default setting "very bright" and I noticed how some board (mostly non Adafruit board) have a white background rather than darker foto booth version.

I feel it would be great for all the image to be with similar background color.

For Unexpected Maker Feather S2, there is such an image...

For other board, maybe someone from Adafruit with graphical skills could spend a bit of time changing white to some background.

PS1: It's best to have a white image than no image...

**Comment by makermelissa** [comment]
Thanks for the suggestion. If you would like to submit a PR for the unexpected maker feather S2 (or any other boards that you're aware of), that would be awesome. However, I don't think there's much value in going through nearly 400 boards and researching if there's light vs dark images available and nobody has volunteered to do so in nearly 2 years.
