### ISSUE TITLE
Downloads Page - Unable to link to a feature with a dash

### ISSUE THREAD

**Issue by jwcooper** [adafruit/circuitpython-org#524]
https://circuitpython.org/downloads?features=Feather-Compatible

That link should work, but ends up back at /downloads after page load (the feature is filtered though).

If you also go to /downloads and select the "Feather-Compatible" feature, it will not populate the url with the selected feature.

**Comment by jwcooper** [comment]
Another issue is a url with special characters, all sorts of issues there. Unable to deselect the feature once set. Page won't load and filter the feature, etc.

Example:
https://circuitpython.org/downloads?manufacturers=Sean+%27xobs%27+Cross

**Comment by makermelissa** [comment]
Ok, it looks like I _may_ have accidentally fixed the features link issue with #552. It's still not populating the URL and the special characters still appears to be an issue.
