### ISSUE TITLE
Need to update bundles with adabot

### ISSUE THREAD

**Issue by makermelissa** [adafruit/circuitpython-org#627]
It appears the requirement to update Nokogiri to the latest has caused the bundles to need updating. According to the GitHub files it looks like something needs to be be run through adabot which I don't have access to. So would somebody with access to adabot please run it?

**Comment by TheKitty** [comment]
Please escalate this request - I am in need of the site being updated for today's publishing of the Python on Microcontrollers Newsletter.

**Comment by makermelissa** [comment]
After speaking with @kattni, I realized I was confused by the naming (and the fact I just woke up possibly). Also, here's a link to the actual failure: https://github.com/adafruit/circuitpython-org/runs/1762887363.

**Comment by TheKitty** [comment]
So is this a non-issue or it still needs repair - the boards on the website are still not displaying
