### ISSUE TITLE
Alphabetize filters

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython-org#674]
@ladyada suggested alphabetizing the manufacturers on the filters page, and doing the same for features would be good too.

![image](https://user-images.githubusercontent.com/2847802/114886008-2f2ceb80-9dd5-11eb-907b-78e8b43887fd.png)

**Comment by dglaude** [comment]
"8086 Consultancy" would totally approve that.
Having a company name starting with an A is smart, but starting with a number is super smart. :-)
