### ISSUE TITLE
/stats doesn't show any stats.

### ISSUE THREAD

**Issue by lesamouraipourpre** [adafruit/circuitpython-org#713]
When viewing https::/circuitpython.org/stats , I get a list of CircuitPython release, the text Board and Downloads in a table and nothing else:
<img width="960" alt="stats1" src="https://user-images.githubusercontent.com/70200140/121089516-29ed8b00-c7df-11eb-8b34-c461277ab9fd.png">

The developer tools view after the javascript has run:
<img width="960" alt="stats2" src="https://user-images.githubusercontent.com/70200140/121089520-2b1eb800-c7df-11eb-8812-76522623b373.png">

**Comment by makermelissa** [comment]
Yeah, it's still not showing stats, but those errors in the developer console are gone so I don't think it's related to that.
