### ISSUE TITLE
Kaluga 2MB == 8Mbit

### ISSUE THREAD

**Issue by lesamouraipourpre** [adafruit/circuitpython-org#717]
In the board pages for the Kaluga (and the Adafruit shop page)
https://github.com/adafruit/circuitpython-org/blob/master/_board/espressif_kaluga_1.md
https://github.com/adafruit/circuitpython-org/blob/master/_board/espressif_kaluga_1.3.md
it states that the board has 2 MB (8 Mbit) PSRAM, surely it should either be:
* 2MB (16Mbit)
* 1MB (8Mbit)

**Comment by makermelissa** [comment]
Oh yeah, I grabbed from the Adafruit product page, which also shows this. @ladyada we probably need to fix this there too.

**Comment by ladyada** [comment]
ok fixed
