### ISSUE TITLE
Make new unknown boards more accessible

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython-org#786]
Currently, when an unknown board is added to CircuitPython, a page like this is generated:
![image](https://user-images.githubusercontent.com/2847802/141814221-48fef573-9761-481b-97f0-3e3a38467bc1.png)
All the links point to `.../unknown...`, etc., which is not too useful.

It would be nice if the board name (`trinket_m0` style, etc.) was used instead, so the new board's builds would at least be accessible before we got around to adding the new boards.

**Comment by tannewt** [comment]
We can likely automate this with the data update for circuitpython.org when we do a release. It really should be something managed with a release.

**Comment by makermelissa** [comment]
> We can likely automate this with the data update for circuitpython.org when we do a release. It really should be something managed with a release.

That's not a bad idea. It would probably look better than what we could do on the website alone.

**Comment by dhalbert** [comment]
Fixed by #869, I believe.

**Comment by makermelissa** [comment]
It still points to `/unknown`, but that's the best we can do on this side with the limitations of liquid and jekyll needing to build the site pages ahead of time. I think the best solution would be to have stubs generated along with the `_data/files.json` as @tannewt suggested.
