### ISSUE TITLE
adafruit pygamer crashes

### ISSUE THREAD

**Issue by Speedycat15** [adafruit/circuitpython-org#806]
MY BRAND NEW PYGAMER IS CRASHED BY YOUR FILE!I CANT DOWNLOAD OTHER THINGS ANYMORE!!!!

**Comment by Speedycat15** [comment]
I HATE THIS

**Comment by dhalbert** [comment]
This is a support issue. Please open a thread in https://forums.adafruit.com/viewforum.php?f=60 or ask for help in #help-with-circuitpython in discord: https://adafru.it/discord. As noted in the forums: "Please be positive and constructive with your questions and comments."

**Comment by Speedycat15** [comment]
thank you so much!
