### ISSUE TITLE
adafruit_feather_esp32s2_bme280 could be an alias?

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython-org#810]
The `adafruit_feather_esp32s2_bme280` has its own description, but the download links don't work, because this board is not a separate board in CircuitPython. The BME280 is just attached to the regular `SCL` and `SDA` pins, so there really would be no difference in the build. So I think this is a candidate for a board alias?

**Comment by makermelissa** [comment]
adafruit_feather_esp32s2_bme280 _is_ an alias, it just looks like it's a bug in my implementation. I'll get a PR submitted to fix this.
