### ISSUE TITLE
http redirection to the docs

### ISSUE THREAD

**Issue by Neradoc** [adafruit/circuitpython-org#873]
The Documentation link at the top of the site links to: https://docs.circuitpython.org/
But that link redirects to: http://docs.circuitpython.org/en/latest/
Without the https. I assume that's on readthedocs ?

**Comment by dhalbert** [comment]
@jwcooper This looks like a typo in wherever the redirects are?

**Comment by jepler** [comment]
In readthedocs I've enabled the checkbox for https.  Note that this _requires_ https (all http URLs redirect to https) but I don't know of any real use cases for reading documentation with a browser that is not https-capable these days.

![image](https://user-images.githubusercontent.com/1517291/155601581-31f2bbbc-1588-420f-8968-5c5e95f7fc66.png)

**Comment by dhalbert** [comment]
This redirecting with https for me now, thanks @jepler!

@jwcooper Never mind!
