### ISSUE TITLE
/stats  for circuitpython.org

### ISSUE THREAD

**Issue by ptorrone** [adafruit/circuitpython-org#98]
would be good to use the github api for up-to-date stats on downloads and have a human-readable page here:

https://www.circuitpython.org/stats

OR

if it's easier, use the JSON file that runs download stats.
https://github.com/adafruit/circuitpython-org/blob/master/_data/files.json

extra extra credit, totally OK with putting google analytics there too so folks can see site traffic, etc.

**Comment by ptorrone** [comment]
@jwcooper @tannewt this is great, would it be possible to display them by top downloads per group?

**Comment by jwcooper** [comment]
@ptorrone what would the group be? Board? Release?

**Comment by ptorrone** [comment]
the download column per group, that way each group is by top downloads?

![adafruit_2019_1758](https://user-images.githubusercontent.com/1685947/55651427-8fd0c900-57b6-11e9-814f-fa1169c339a5.jpg)

**Comment by ptorrone** [comment]
@jwcooper just talked with @tannewt each release would be sorted by downloads (most being at the top of each release).

**Comment by tannewt** [comment]
My understanding is that the top release shown would be the one with the most total downloads (3.1.2 now I think.)

**Comment by ptorrone** [comment]
i meant the latest release is still at the top, and within that, top downloads.

**Comment by ptorrone** [comment]
OK! it appears that firefox as per @tannewt displays it correctly but it's chrome that does not, all this time... sorry @jwcooper for the comments here, so this is now a chrome display issue :(

here is what it looks like on chrome.

![adafruit_2019_1760](https://user-images.githubusercontent.com/1685947/55654466-72542d00-57bf-11e9-9619-f49911bc0eed.jpg)

**Comment by sommersoft** [comment]
> so this is now a chrome display issue

Also an Edge issue, as it displays "non-sorted" as well.

**Comment by cpforbes** [comment]
The sort comparison function isn't returning the right thing. It should be:

`return b.downloads - a.downloads`
to get highest to lowest.

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#Description

**Comment by jwcooper** [comment]
Pushed a pr for the fix: https://github.com/adafruit/circuitpython-org/pull/118

**Comment by sommersoft** [comment]
Confirm that #118 fixes for Edge as well. Thanks @cpforbes & @jwcooper.
